### PR TITLE
Fix arch's terrible python

### PR DESCRIPTION
**Pull request by piecubed**

### CODE REVIEW

**Review by archfan7411 — CHANGES_REQUESTED** [review]
The added `PIN` constant and spacing fixes are good, but the comments I'd like to keep - aside from the import comments, those can burn.

**Comment by piecubed** [comment]
I am the python master do not challenge me

**Review by archfan7411 — CHANGES_REQUESTED** [review]
I do challenge you

**Comment by piecubed** [comment]
Where shall we duel

**Comment by archfan7411** [comment]
Here, where else

**Comment by archfan7411** [comment]
Let me try my first attack move

**Comment by archfan7411** [comment]
It's successful

**Comment by piecubed** [comment]
My only weakness

**Comment by piecubed** [comment]
However that was not an attack via python

**Comment by piecubed** [comment]
Do reopen this PR and challenge me again, only in python

**Comment by archfan7411** [comment]
Why would I attack the Python master using Python

**Comment by piecubed** [comment]
Because using a graphical git interface requires no skill

**Comment by archfan7411** [comment]
I'll have you know that all my commits aside from the first two were done from commandline

**Comment by piecubed** [comment]
Ah but you still havent seen my challenge, reopen this PR and then close it using python and it may dissapear

**Comment by archfan7411** [comment]
I fear I must now go AFK

**Comment by piecubed** [comment]
You weak graphical user

**Pull request closed without merging**
